### PR TITLE
Dof

### PR DESCRIPTION
**Pull request by daniekpo**
Depth of field sorta working.

______
Don't forget to update the readme in the holodeck repo :)

### CODE REVIEW

**Comment by daniekpo** [comment]
@MaxRobinsonTheGreat did you get a chance to take a look at this?

**Comment by daniekpo** [comment]
@jaydenmilne and @vinhowe if you have some time to take a look at this too and let me know what you think that'd be great.

**Comment by vinhowe** [comment]
It looks like some of the changes here are old changes that I thought were already merged in. Can you verify that everything in the diff is related to the PR as it stands?

**Comment by vinhowe** [comment]
I'm not sure what's going on with the old commits, but they disappeared when I changed the base to master. What if you merge in develop?

**Comment by daniekpo** [comment]
I'm going to close this PR for now so we can focus on other things. I'll revisit this later in the future.

**Pull request closed without merging**
